# Generated by Django 4.0 on 2022-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=40)),
                ('barangay', models.CharField(max_length=40)),
            ],
        ),
    ]
