# Generated by Django 4.0 on 2022-09-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeeds',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default=None, max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='newsfeeds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuser')),
            ],
        ),
    ]
