# Generated by Django 4.0 on 2022-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeeds',
            name='category',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='newsfeeds',
            name='photo',
            field=models.ImageField(default=None, upload_to='newsfeeds'),
        ),
    ]
