# Generated by Django 4.0 on 2022-09-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_dtcaccount_user_customuser'),
        ('backendapi', '0002_newsfeeds_category_newsfeeds_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeeds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuser'),
        ),
    ]
