# Generated by Django 4.0 on 2022-08-18 00:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserThumbNail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='photos')),
            ],
        ),
    ]
