# Generated by Django 4.0 on 2022-08-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthumbnail',
            name='say',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
