# Generated by Django 4.0 on 2022-08-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtcaccount',
            name='profile_pic',
        ),
    ]
