# Generated by Django 4.0 on 2022-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthumbnail',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
