# Generated by Django 4.0 on 2022-08-13 20:08

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthumbnail',
            name='id',
        ),
        migrations.AddField(
            model_name='userthumbnail',
            name='_id',
            field=models.AutoField(default='tamina', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userthumbnail',
            name='photo',
            field=models.ImageField(storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
