# Generated by Django 4.0 on 2022-08-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('num_stars', models.IntegerField()),
                ('file', models.BinaryField()),
            ],
        ),
    ]
