# Generated by Django 4.0 on 2022-08-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DtcModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeeds',
            name='photo',
        ),
    ]
