# Generated by Django 4.0 on 2022-08-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_dtcaccount_profile_pic'),
        ('DtcModels', '0003_photo_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='news',
        ),
        migrations.DeleteModel(
            name='NewsFeeds',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
